#!/usr/bin/env escript
%% -*- erlang -*-

main([]) ->

    ensure_config(),
    Node = get_node(),
    PipeDir = "/tmp/" ++ Node ++ "/",

    filelib:ensure_dir("var/runerl_log/"),
    filelib:ensure_dir(PipeDir),

    Cmd = "run_erl -daemon " ++ PipeDir ++ " var/runerl_log "
        ++ "\"erl -name " ++ Node ++ " "
        ++ "-pa ./deps/mochiweb/ebin ./deps/mochiweb_xpath/ebin ./ebin "
        ++ "-config var/sys.config "
        ++ "-run start start\"",

    case os:cmd(Cmd) of
        []   ->
            ok,
            make_shell(Node);
        Else ->
            io:format("Hypernumbers failed to boot:~n~s~n",[Else]),
            ok
    end.

ensure_config() ->
    case has_config() of
        false -> copy_default_config();
        true  -> ok
    end.

copy_default_config() ->
    ok = filelib:ensure_dir([root(), "/var/"]),
    {ok, _Bytes} =
        file:copy([root(), "/priv/", "sys.config.default"], config_file()),
    ok.

config_file() ->
    [root(), "/var/", "sys.config"].

root() ->
    {ok, Root} = file:get_cwd(),
    Root.

has_config() ->
    filelib:is_file(config_file()).

get_node() -> "spiderl".

make_shell(NodeName) ->
    Shell = io_lib:format("#!/bin/bash~nto_erl /tmp/~s/~n", [NodeName]),
    file:write_file("shell", Shell),
    os:cmd("chmod +x shell").
